/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-content-panel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

/**
 * `etools-content-panel`
 * A simple panel with header to display a collapsible content.
 *
 * ### Styling
 *
 * You can use defined variables and mixins to change panel style.
 *
 * Custom property | Description | Default
 * ----------------|-------------|----------
 * `--ecp-header-height` | Header height | `48px`
 * `--ecp-header-bg` | Header background color | `#1e86bf`
 * `--ecp-header-color` | Header color | `#ffffff`
 * `--ecp-header` | Mixin applied to header | `{}`
 * `--ecp-toggle-btn` | Mixin applied to expand content button | `{}`
 * `--ecp-header-title` | Mixin applied to the header title | `{}`
 * `--ecp-header-btns-wrapper` | Mixin appplied to panel header right btns container | `{}`
 * `--ecp-content` | Mixin applied to content | `{}`
 * `--ecp-disabled` | Mixin applied in disabled state | `{}`
 */
declare class EtoolsContentPanel extends PolymerElement {
  panelTitle: string|null|undefined;
  elevation: number|null|undefined;
  open: boolean|null|undefined;
  noHeader: boolean|null|undefined;
  disabled: boolean|null|undefined;
  showExpandBtn: boolean|null|undefined;
  _toggle(): void;
  _getExpandBtnIcon(open: any): any;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-content-panel": EtoolsContentPanel;
  }
}
